<?xml version="1.0" encoding="utf-8"?><Database Name="sinfo" Class="RentingDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=D-Komputer;Initial Catalog=sinfo;Integrated Security=True" SettingsObjectName="Renting.Ria.Web.Properties.Settings" SettingsPropertyName="sinfoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.rezerwacje" Member="rezerwacjes">
    <Type Name="rezerwacje">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="data_wypozyczenia" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="data_zwrotu" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="pracownik_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="klient_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="samochod_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="uwagi" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="status_" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>