#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renting.Ria.Web
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sinfo")]
	public partial class RentingDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertrezerwacje(rezerwacje instance);
    partial void Updaterezerwacje(rezerwacje instance);
    partial void Deleterezerwacje(rezerwacje instance);
    #endregion
		
		public RentingDataClassesDataContext() : 
				base(global::Renting.Ria.Web.Properties.Settings.Default.sinfoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public RentingDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RentingDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RentingDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public RentingDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<rezerwacje> rezerwacjes
		{
			get
			{
				return this.GetTable<rezerwacje>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rezerwacje")]
	public partial class rezerwacje : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.DateTime _data_wypozyczenia;
		
		private System.Nullable<System.DateTime> _data_zwrotu;
		
		private int _pracownik_id;
		
		private int _klient_id;
		
		private int _samochod_id;
		
		private string _uwagi;
		
		private string _status_;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Ondata_wypozyczeniaChanging(System.DateTime value);
    partial void Ondata_wypozyczeniaChanged();
    partial void Ondata_zwrotuChanging(System.Nullable<System.DateTime> value);
    partial void Ondata_zwrotuChanged();
    partial void Onpracownik_idChanging(int value);
    partial void Onpracownik_idChanged();
    partial void Onklient_idChanging(int value);
    partial void Onklient_idChanged();
    partial void Onsamochod_idChanging(int value);
    partial void Onsamochod_idChanged();
    partial void OnuwagiChanging(string value);
    partial void OnuwagiChanged();
    partial void Onstatus_Changing(string value);
    partial void Onstatus_Changed();
    #endregion
		
		public rezerwacje()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_wypozyczenia", DbType="Date NOT NULL")]
		public System.DateTime data_wypozyczenia
		{
			get
			{
				return this._data_wypozyczenia;
			}
			set
			{
				if ((this._data_wypozyczenia != value))
				{
					this.Ondata_wypozyczeniaChanging(value);
					this.SendPropertyChanging();
					this._data_wypozyczenia = value;
					this.SendPropertyChanged("data_wypozyczenia");
					this.Ondata_wypozyczeniaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_zwrotu", DbType="Date")]
		public System.Nullable<System.DateTime> data_zwrotu
		{
			get
			{
				return this._data_zwrotu;
			}
			set
			{
				if ((this._data_zwrotu != value))
				{
					this.Ondata_zwrotuChanging(value);
					this.SendPropertyChanging();
					this._data_zwrotu = value;
					this.SendPropertyChanged("data_zwrotu");
					this.Ondata_zwrotuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pracownik_id", DbType="Int NOT NULL")]
		public int pracownik_id
		{
			get
			{
				return this._pracownik_id;
			}
			set
			{
				if ((this._pracownik_id != value))
				{
					this.Onpracownik_idChanging(value);
					this.SendPropertyChanging();
					this._pracownik_id = value;
					this.SendPropertyChanged("pracownik_id");
					this.Onpracownik_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_klient_id", DbType="Int NOT NULL")]
		public int klient_id
		{
			get
			{
				return this._klient_id;
			}
			set
			{
				if ((this._klient_id != value))
				{
					this.Onklient_idChanging(value);
					this.SendPropertyChanging();
					this._klient_id = value;
					this.SendPropertyChanged("klient_id");
					this.Onklient_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_samochod_id", DbType="Int NOT NULL")]
		public int samochod_id
		{
			get
			{
				return this._samochod_id;
			}
			set
			{
				if ((this._samochod_id != value))
				{
					this.Onsamochod_idChanging(value);
					this.SendPropertyChanging();
					this._samochod_id = value;
					this.SendPropertyChanged("samochod_id");
					this.Onsamochod_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uwagi", DbType="VarChar(50)")]
		public string uwagi
		{
			get
			{
				return this._uwagi;
			}
			set
			{
				if ((this._uwagi != value))
				{
					this.OnuwagiChanging(value);
					this.SendPropertyChanging();
					this._uwagi = value;
					this.SendPropertyChanged("uwagi");
					this.OnuwagiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string status_
		{
			get
			{
				return this._status_;
			}
			set
			{
				if ((this._status_ != value))
				{
					this.Onstatus_Changing(value);
					this.SendPropertyChanging();
					this._status_ = value;
					this.SendPropertyChanged("status_");
					this.Onstatus_Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
