#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsManagement.Ria.Web
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="sinfo")]
	public partial class CarsManagementDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertsamochody(samochody instance);
    partial void Updatesamochody(samochody instance);
    partial void Deletesamochody(samochody instance);
    #endregion
		
		public CarsManagementDataClassesDataContext() : 
				base(global::CarsManagement.Ria.Web.Properties.Settings.Default.sinfoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CarsManagementDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarsManagementDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarsManagementDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CarsManagementDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<samochody> samochodies
		{
			get
			{
				return this.GetTable<samochody>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.samochody")]
	public partial class samochody : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _marka;
		
		private short _rok_produkcji;
		
		private bool _oc;
		
		private bool _ac;
		
		private bool _nw;
		
		private string _opis;
		
		private string _status_;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmarkaChanging(string value);
    partial void OnmarkaChanged();
    partial void Onrok_produkcjiChanging(short value);
    partial void Onrok_produkcjiChanged();
    partial void OnocChanging(bool value);
    partial void OnocChanged();
    partial void OnacChanging(bool value);
    partial void OnacChanged();
    partial void OnnwChanging(bool value);
    partial void OnnwChanged();
    partial void OnopisChanging(string value);
    partial void OnopisChanged();
    partial void Onstatus_Changing(string value);
    partial void Onstatus_Changed();
    #endregion
		
		public samochody()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_marka", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string marka
		{
			get
			{
				return this._marka;
			}
			set
			{
				if ((this._marka != value))
				{
					this.OnmarkaChanging(value);
					this.SendPropertyChanging();
					this._marka = value;
					this.SendPropertyChanged("marka");
					this.OnmarkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rok_produkcji", DbType="SmallInt NOT NULL")]
		public short rok_produkcji
		{
			get
			{
				return this._rok_produkcji;
			}
			set
			{
				if ((this._rok_produkcji != value))
				{
					this.Onrok_produkcjiChanging(value);
					this.SendPropertyChanging();
					this._rok_produkcji = value;
					this.SendPropertyChanged("rok_produkcji");
					this.Onrok_produkcjiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_oc", DbType="Bit NOT NULL")]
		public bool oc
		{
			get
			{
				return this._oc;
			}
			set
			{
				if ((this._oc != value))
				{
					this.OnocChanging(value);
					this.SendPropertyChanging();
					this._oc = value;
					this.SendPropertyChanged("oc");
					this.OnocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ac", DbType="Bit NOT NULL")]
		public bool ac
		{
			get
			{
				return this._ac;
			}
			set
			{
				if ((this._ac != value))
				{
					this.OnacChanging(value);
					this.SendPropertyChanging();
					this._ac = value;
					this.SendPropertyChanged("ac");
					this.OnacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nw", DbType="Bit NOT NULL")]
		public bool nw
		{
			get
			{
				return this._nw;
			}
			set
			{
				if ((this._nw != value))
				{
					this.OnnwChanging(value);
					this.SendPropertyChanging();
					this._nw = value;
					this.SendPropertyChanged("nw");
					this.OnnwChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_opis", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string opis
		{
			get
			{
				return this._opis;
			}
			set
			{
				if ((this._opis != value))
				{
					this.OnopisChanging(value);
					this.SendPropertyChanging();
					this._opis = value;
					this.SendPropertyChanged("opis");
					this.OnopisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string status_
		{
			get
			{
				return this._status_;
			}
			set
			{
				if ((this._status_ != value))
				{
					this.Onstatus_Changing(value);
					this.SendPropertyChanging();
					this._status_ = value;
					this.SendPropertyChanged("status_");
					this.Onstatus_Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
